// <auto-generated />
using System;
using MachinePro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MachinePro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MachinePro.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Administrator",
                            Password = "admin",
                            Role = "Manager",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MachinePro.Models.CapacityLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntryDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MachineBuildNumber")
                        .HasColumnType("text");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("QtyProduced")
                        .HasColumnType("integer");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CapacityLedgerEntries");
                });

            modelBuilder.Entity("MachinePro.Models.CustomerMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CustomerMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "India",
                            CustomerName = "Tata Motors"
                        },
                        new
                        {
                            Id = 2,
                            Country = "India",
                            CustomerName = "Reliance Ind"
                        },
                        new
                        {
                            Id = 3,
                            Country = "India",
                            CustomerName = "L&T Heavy"
                        },
                        new
                        {
                            Id = 4,
                            Country = "India",
                            CustomerName = "Bajaj Auto"
                        },
                        new
                        {
                            Id = 5,
                            Country = "India",
                            CustomerName = "Mahindra & Mahindra"
                        });
                });

            modelBuilder.Entity("MachinePro.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompletedDate")
                        .HasColumnType("text");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Drawing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrawingDescription")
                        .HasColumnType("text");

                    b.Property<string>("InwardDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemCode")
                        .HasColumnType("text");

                    b.Property<string>("MachineBuildNumber")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Process1")
                        .HasColumnType("text");

                    b.Property<string>("Process2")
                        .HasColumnType("text");

                    b.Property<string>("Process3")
                        .HasColumnType("text");

                    b.Property<string>("Process4")
                        .HasColumnType("text");

                    b.Property<string>("Process5")
                        .HasColumnType("text");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Customer = "Tata Motors",
                            Drawing = "DWG-2201",
                            DrawingDescription = "Engine block housing plate",
                            InwardDate = "24/03/2026",
                            IsCompleted = false,
                            Model = "TM-400X",
                            Process1 = "VMC",
                            Process2 = "Milling",
                            Process3 = "Lathe",
                            Qty = 12,
                            Serial = "SN-001"
                        },
                        new
                        {
                            Id = 2,
                            Customer = "Reliance Ind",
                            Drawing = "DWG-3302",
                            DrawingDescription = "Pump shaft coupling",
                            InwardDate = "24/03/2026",
                            IsCompleted = false,
                            Model = "RI-750",
                            Process1 = "Lathe",
                            Process2 = "Shaper",
                            Qty = 8,
                            Serial = "SN-002"
                        });
                });

            modelBuilder.Entity("MachinePro.Models.ModelMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModelMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModelName = "TM-400X"
                        },
                        new
                        {
                            Id = 2,
                            ModelName = "TM-500Y"
                        },
                        new
                        {
                            Id = 3,
                            ModelName = "RI-750"
                        },
                        new
                        {
                            Id = 4,
                            ModelName = "LT-900K"
                        },
                        new
                        {
                            Id = 5,
                            ModelName = "BA-200Z"
                        },
                        new
                        {
                            Id = 6,
                            ModelName = "MM-600A"
                        });
                });

            modelBuilder.Entity("MachinePro.Models.ModuleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FinishedDate")
                        .HasColumnType("text");

                    b.Property<int?>("FinishedQty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<string>("MachineBuildNumber")
                        .HasColumnType("text");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("text");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("ModuleEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsFinished = false,
                            JobId = 1,
                            ModuleName = "VMC"
                        },
                        new
                        {
                            Id = 2,
                            IsFinished = false,
                            JobId = 1,
                            ModuleName = "Milling"
                        },
                        new
                        {
                            Id = 3,
                            IsFinished = false,
                            JobId = 1,
                            ModuleName = "Lathe"
                        },
                        new
                        {
                            Id = 4,
                            IsFinished = false,
                            JobId = 2,
                            ModuleName = "Lathe"
                        },
                        new
                        {
                            Id = 5,
                            IsFinished = false,
                            JobId = 2,
                            ModuleName = "Shaper"
                        });
                });

            modelBuilder.Entity("MachinePro.Models.PlannerHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("PlannerHistories");
                });

            modelBuilder.Entity("MachinePro.Models.ModuleEntry", b =>
                {
                    b.HasOne("MachinePro.Models.Job", "Job")
                        .WithMany("ModuleEntries")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MachinePro.Models.Job", b =>
                {
                    b.Navigation("ModuleEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
